### ISSUE TITLE
Writing POINTZ does not work correctly

### ISSUE THREAD

**Issue by domlysz** [GeospatialPython/pyshp#102]
Hi, 

below the test code

```python
from shapefile import Writer as shpWriter, Reader as shpReader
from shapefile import POINTZ, POLYLINEZ, POLYGONZ

import os
folder = os.path.dirname(os.path.abspath(__file__))

outShp = shpWriter(POINTZ)
outShp.field('id','N','10')
outShp.point(10, 10, 10)
outShp.record(0)
outPath = folder + os.sep + 'out.shp'
outShp.save(outPath)

shp = shpReader(outPath)
shape = shp.shapes()[0]
xy = shape.points[0]
z = shape.z[0]
print(xy, z)
```

work correctly with pyshp 1.2.3 but raise an error with v 1.2.11

AttributeError: _Shape instance has no attribute 'z'

**Comment by karimbahgat** [comment]
Not sure which part of 1.2.11 caused this change, but the fact that it worked in older versions was probably more of an error/oversight. The code you showed defines the shapefile as POINTZ, but in the point() method it also needed to set the shapeType to POINTZ (the default is POINT). The fact that you specified a z-value didn't change the shapeType (it probably should have). Thus when it saved the file it only wrote the xy values, and hence no z-value when you read it back in. I think version 1.2.3 did not notice when you wrote a shapeType that did not match with the shapefile, but now it raises an exception. 

Nevertheless, since it's easy to forget setting the shapeType argument, as of 0c182098e614e9274e638488a19af7a12674b532 there is a designated method for each shape type, so there is no longer the need for a separate shapeType argument. So in your case, you would simply change `outShp.point(10, 10, 10)` to `outShp.pointz(10, 10, 10)`.
